# Generated by Django 5.1.6 on 2025-02-20 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='banners/')),
            ],
        ),
        migrations.CreateModel(
            name='aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ourstory', models.TextField()),
                ('storyimg', models.ImageField(upload_to='about/')),
                ('quality', models.TextField()),
                ('qualityimg', models.ImageField(upload_to='about/')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Blog_image', models.ImageField(upload_to='blog/')),
                ('heading', models.CharField(max_length=300)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='banners/')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(unique=True)),
                ('front_image', models.ImageField(upload_to='catalog_images/')),
                ('back_image', models.ImageField(upload_to='catalog_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='copyrights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Copyrights', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner1', models.ImageField(upload_to='home/')),
                ('banner2', models.ImageField(upload_to='home/')),
                ('banner3', models.ImageField(upload_to='home/')),
                ('banner4', models.ImageField(upload_to='home/')),
                ('welcome_image', models.ImageField(upload_to='home/')),
                ('welcome_description', models.TextField()),
                ('gallery1', models.ImageField(default='default_image.jpg', upload_to='home/')),
                ('gallery2', models.ImageField(default='default_image.jpg', upload_to='home/')),
                ('gallery3', models.ImageField(default='default_image.jpg', upload_to='home/')),
                ('gallery4', models.ImageField(default='default_image.jpg', upload_to='home/')),
                ('gallery5', models.ImageField(default='default_image.jpg', upload_to='home/')),
                ('gallery6', models.ImageField(default='default_image.jpg', upload_to='home/')),
                ('gallery7', models.ImageField(default='default_image.jpg', upload_to='home/')),
                ('gallery8', models.ImageField(default='default_image.jpg', upload_to='home/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='products/')),
                ('homeproductimage', models.ImageField(upload_to='products/')),
                ('url_name', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='banners/')),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.URLField(blank=True, default='https://www.instagram.com/')),
                ('linkedin', models.URLField(blank=True, default='https://www.linkedin.com/')),
                ('facebook', models.URLField(blank=True, default='https://www.facebook.com/')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='testimonials/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SubProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('before_image', models.ImageField(upload_to='subproducts/')),
                ('after_image', models.ImageField(upload_to='subproducts/')),
                ('url_name', models.SlugField(unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subproducts', to='home.product')),
            ],
        ),
        migrations.CreateModel(
            name='SubProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='subproduct_categories/')),
                ('url_name', models.SlugField(unique=True)),
                ('subproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='home.subproduct')),
            ],
        ),
        migrations.CreateModel(
            name='SubProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='home.subproductcategory')),
            ],
        ),
    ]
