# Generated by Django 5.1.6 on 2025-02-20 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subproductdetail',
            name='category',
        ),
        migrations.AddField(
            model_name='subproductdetail',
            name='subproduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='home.subproduct'),
        ),
        migrations.CreateModel(
            name='SubSubProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('before_image', models.ImageField(upload_to='subsubproducts/')),
                ('after_image', models.ImageField(upload_to='subsubproducts/')),
                ('url_name', models.SlugField(unique=True)),
                ('subproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsubproducts', to='home.subproduct')),
            ],
        ),
        migrations.AddField(
            model_name='subproductdetail',
            name='subsubproduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='home.subsubproduct'),
        ),
    ]
