# Generated by Django 5.1.6 on 2025-02-20 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_subproductdetail_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsubproduct',
            name='subproduct',
        ),
        migrations.RemoveField(
            model_name='subproductdetail',
            name='subsubproduct',
        ),
        migrations.AlterField(
            model_name='subproductdetail',
            name='subproduct',
            field=models.ForeignKey(default=2.5, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='home.subproduct'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SubProductCategory',
        ),
        migrations.DeleteModel(
            name='SubSubProduct',
        ),
    ]
