services:
  - type: web
    name: luxxon
    env: python
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn meetmetal.wsgi:application
    branch: main
    plan: free
