services:
  - type: web
    name: luxxon-hw
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn meetmetal.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
