services:
  - type: web
    name: luxxon
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn meetmetal.wsgi:application
 