services:
  - type: web
    name: luxxon-hw
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python manage.py runserver 0.0.0.0:$PORT