services:
  - type: web
    name: luxxon-django-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn your_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
