services:
  - type: web
    name: luxxon
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install --upgrade setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn meetmetal.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
    build:
      environment:
        PYTHON_VERSION: 3.11.9
